name: secciones
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - seaborn
  - pandas
  - geopandas
  - numpy
  - matplotlib
  - dash
  - plotly
  - jupyter
  - openpyxl
  - psycopg2
  - python-dotenv
  - fastapi
